name: Rust Checks

permissions: read-all

on: [push, pull_request]

jobs:
  Build-Format-Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Build check
        run: cargo build

      - name: Formatting check
        run: cargo fmt -v --all --check

      - name: Lint/static analysis check
        run: cargo clippy --all-targets -- -Dwarnings
