name: Bash Format

on: [push, pull_request]

jobs:
  shfmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install shfmt
        run: |
          sudo apt update && sudo apt install -y shfmt

      - name: Run Bash formatter
        run: shfmt -ln bash -d -- *.sh
